import { useEffect, useRef, useState } from 'react'
import { io } from 'socket.io-client'
import { CLIENT_TOKEN_KEY } from '../../api/clientAxios'
import { listClientNotifications, markAllClientNotificationsRead, markClientNotificationRead } from '../../api/clientPortal'
import { useClientAuth } from '../../context/ClientAuthContext'
import { C, S, font } from '../../components/common/theme'
import { Button, Card, Spinner } from '../../components/common/ui'

const socketUrl = import.meta.env.VITE_SOCKET_URL || import.meta.env.VITE_API_BASE_URL?.replace(/\/api\/?$/, '') || 'http://localhost:5000'
export default function ClientNotifications(){const {client}=useClientAuth();const [items,setItems]=useState(null);const socketRef=useRef(null);useEffect(()=>{if(!client?.id)return;listClientNotifications().then(d=>setItems(d.notifications||[])).catch(()=>setItems([]));const token=localStorage.getItem(CLIENT_TOKEN_KEY);const socket=io(socketUrl,{transports:['websocket','polling'],auth:{token}});socketRef.current=socket;socket.on('connect',()=>socket.emit('registerUser',{userId:client.id}));socket.on('newNotification',n=>setItems(prev=>[n,...(prev||[])]));return()=>socket.disconnect()},[client?.id]);if(!items)return <Spinner label="Loading notifications"/>;const unread=items.filter(n=>!n.read).length;const markAll=async()=>{await markAllClientNotificationsRead();setItems(items.map(n=>({...n,read:true})))};const mark=async(id)=>{await markClientNotificationRead(id);setItems(items.map(n=>n._id===id?{...n,read:true}:n))};return <div><div style={{display:'flex',justifyContent:'space-between',marginBottom:24,alignItems:'end'}}><div><div style={S.eyebrow}>CLIENT PORTAL</div><h1 style={S.h1}>Notifications</h1><div style={{fontSize:11,color:C.dim,fontFamily:font.mono}}>{unread} unread</div></div><Button variant="ghost" onClick={markAll} disabled={!unread}>Mark all read</Button></div><Card>{items.length?items.slice(0,30).map(n=><button key={n._id} type="button" onClick={()=>mark(n._id)} style={{display:'block',width:'100%',textAlign:'left',padding:16,border:0,borderBottom:`1px solid ${C.line}`,background:n.read?'transparent':'rgba(45,143,106,0.08)',color:C.text,cursor:n.read?'default':'pointer'}}><div style={{fontSize:12,fontWeight:700}}>{n.title}</div><div style={{fontSize:11,color:C.muted,marginTop:4}}>{n.message}</div><div style={{fontSize:8,color:C.dim,fontFamily:font.mono,marginTop:6}}>{new Date(n.createdAt).toLocaleString()}</div></button>):<div style={{padding:20,color:C.dim,fontSize:12}}>No notifications.</div>}</Card></div>}
