import { useEffect, useRef, useState } from 'react'
import { io } from 'socket.io-client'
import { getMessages, markMessagesRead } from '../../api/chat'
import { TOKEN_KEY } from '../../api/axiosInstance'
import MessageBubble from './MessageBubble'
import { C, S, font } from '../common/theme'

const socketUrl = import.meta.env.VITE_SOCKET_URL || import.meta.env.VITE_API_BASE_URL?.replace(/\/api\/?$/, '') || 'http://localhost:5000'

export default function ChatWindow({ therapistId, clientId, currentUserId }) {
  const [messages,setMessages]=useState([]);const [text,setText]=useState('');const [typing,setTyping]=useState(false);const [connected,setConnected]=useState(false)
  const socketRef=useRef(null);const timer=useRef(null)
  useEffect(()=>{if(!therapistId||!clientId||!currentUserId)return;let active=true;(async()=>{try{const data=await getMessages(clientId);if(active)setMessages(data.messages||[]);await markMessagesRead(clientId)}catch(err){console.error('Unable to load chat:',err)}})();const token=localStorage.getItem(TOKEN_KEY);const socket=io(socketUrl,{transports:['websocket','polling'],auth:{token}});socketRef.current=socket;socket.on('connect',()=>{setConnected(true);socket.emit('joinConversation',{therapistId,clientId});socket.emit('markRead',{therapistId,clientId})});socket.on('disconnect',()=>setConnected(false));socket.on('messagesRead', ({ userId }) => { if (String(userId) !== String(currentUserId)) setMessages((prev) => prev.map((m) => String(m.sender) === String(currentUserId) ? { ...m, read: true } : m)) })
    socket.on('newMessage',m=>setMessages(prev=>prev.some(x=>x._id===m._id)?prev:[...prev,m]));socket.on('userTyping',({userId})=>{if(String(userId)!==String(currentUserId))setTyping(true)});socket.on('userStoppedTyping',({userId})=>{if(String(userId)!==String(currentUserId))setTyping(false)});return()=>{active=false;clearTimeout(timer.current);socket.disconnect();socketRef.current=null}},[therapistId,clientId,currentUserId])
  const change=(value)=>{setText(value);const s=socketRef.current;if(!s)return;s.emit('typing',{therapistId,clientId});clearTimeout(timer.current);timer.current=setTimeout(()=>s.emit('stopTyping',{therapistId,clientId}),700)}
  const send=()=>{const value=text.trim();const s=socketRef.current;if(!value||!s||!connected)return;s.emit('sendMessage',{therapistId,clientId,text:value});setText('')}
  return <div style={{height:'100%',minHeight:0,display:'flex',flexDirection:'column',background:C.bg}}><div style={{minHeight:58,padding:'10px 18px',display:'flex',alignItems:'center',justifyContent:'space-between',borderBottom:`1px solid ${C.line}`,background:C.side}}><div><div style={{fontSize:13,fontWeight:600,color:C.text}}>Client conversation</div><div style={{marginTop:2,fontSize:9,color:connected?C.mint:C.dim,fontFamily:font.mono}}><span style={{display:'inline-block',width:5,height:5,borderRadius:'50%',background:connected?C.green:C.dim,marginRight:5}}/>{connected?'Connected':'Connecting...'}</div></div><div style={{fontSize:9,color:C.dim,fontFamily:font.mono}}>Secure conversation</div></div><div style={{flex:1,minHeight:0,overflowY:'auto',padding:'18px 20px'}}>{messages.length?<div style={{display:'flex',flexDirection:'column',gap:8}}>{messages.map(m=><MessageBubble key={m._id} message={m} currentUserId={currentUserId}/>)}</div>:<div style={{height:'100%',minHeight:280,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:7,color:C.dim,fontSize:12}}>No messages yet. Start the conversation.</div>}{typing&&<div style={{marginTop:10,fontSize:10,color:C.dim,fontFamily:font.mono}}>Client is typing...</div>}</div><div style={{padding:12,borderTop:`1px solid ${C.line}`,background:C.side}}><div style={{display:'flex',alignItems:'flex-end',gap:8}}><textarea value={text} onChange={e=>change(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Write a message..." rows={2} style={{...S.input,flex:1,resize:'none',minHeight:42,maxHeight:100}}/><button type="button" onClick={send} disabled={!text.trim()||!connected} style={{...S.btnPrimary,height:42,padding:'0 17px',fontSize:11,opacity:(!text.trim()||!connected)?0.45:1}}>Send</button></div><div style={{marginTop:5,fontSize:9,color:C.dim,fontFamily:font.mono}}>Enter to send · Shift + Enter for a new line</div></div></div>
}
